print("Hospital Appointment Booking System features added")
print("Patient Registration Module Added")
print("Appointment Scheduling Module Added")
print("Login Feature Added")
print("Login page created")